### ISSUE TITLE
FYI: libfap 1.5 was released to address a crash

### ISSUE THREAD

**Issue by bradanlane** [Turbo87/libfap#1]
from the ChangeLog:
libfap 1.5: \* Fixed a crash in fapint_parse_comment_telemetry

the salient change appears to be just at the start of the function:

```
    if ( rest == 0 || *rest == 0 || rest_len == 0 || *rest_len == 0 )
    {
        return;
    }

    /* Look for base91-telemetry. */
```

**Comment by Turbo87** [comment]
thanks for letting me know. I don't use this library anymore so the mirror isn't really up to date.

**Comment by bradanlane** [comment]
Gotcha. I "inherited" a project which uses the Perl version but it really needs to get ported and when I found `libfap` I decided I'd go with it. 

If you don't plan to use the github project, would it make sense to sunset it?

**Comment by Turbo87** [comment]
unfortunately there is no "deprecated" option in the project settings at GitHub and I don't want to mess with the commit history in case someone would like to continue what I started here.
